npmAuthToken: NTRlNmVjZDcyMjU1MzU0NjIwZjJjMjE5NDk4Y2Y5Nzc6Yzg5MjQyNTVkNjFhMWQ=

npmRegistryServer: "http://localhost:4873"

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-4.5.3.cjs
